### ISSUE TITLE
Fix migrations due mismaching pallet versions

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1732]
### Description

Executing the node with `try-runtime` is actually failing in `Altair` & `centrifuge`. We should fix them before the next RU. Reasons:
- ~~Some pallets have increased their version number without adding a migration.~~
   - ~~I think most of these pallets can just reuse the same version number because the previous versions were killed (i.e. oracle-feed, loans, oracle-collection).~~ => #1641 + orderbook
- (warn) A migration of `pool-system` is failing because we've pumped up `pool-system` to a new version (with pool fees) before applying a pending migration. Now, the migration expect an old version number for `pool-system` and it's not applied. 
   - I'm not sure of the best way we can solve this, maybe adding a new migration for pool-fees increasing the version number there? @wischli

**Comment by wischli** [comment]
This is an extension of https://github.com/centrifuge/centrifuge-chain/issues/1641. I started looking into the external pallets and will push that soon. Unfortunately, we will only know if it works, after the changes are live because `try-runtime` only works on the overlay and will still panic against the upstream data from the node.

**Comment by lemunozm** [comment]
I guess we can close this now
