### ISSUE TITLE
Revert to separate reserve changes calculation

### ISSUE THREAD

**Issue by offerijns** [centrifuge/centrifuge-chain#599]
With a low reserve, any single tranche having more redemptions than investments could cause this to underflow now and we'd flag an error. That seems more likely than the total of investments or the total of redemptions individually overflowing, and is why I precalculated those totals before.

_Originally posted by @branan in https://github.com/centrifuge/centrifuge-chain/pull/588#discussion_r786147725_

**Comment by mustermeiszer** [comment]
@branan Regarding this. If we have an underflow in the `do_execute_epoch` doesn`t this mean we missed something early on? This basically means, we have an epoch execution that wipes out the pool. So Reverting to separate calculations is not really helpful here.

**Comment by mustermeiszer** [comment]
If the above is the case, I would close this one here.

**Comment by branan** [comment]
The underflow isn't due to actual constraint violations, but due to order of operations. Originally we did something like this:

`reserve = reserve + total_investments - total_redemptions`

Now we do this:

```
for each tranche:
    reserve = reserve + tranche_investments - tranche_redemptions
```

The issue here is that a single tranche with a large number of redemptions can cause an arithmetic underflow, even if we have the investments to balance things out in another tranche that we haven't gotten to yet.

**Comment by mustermeiszer** [comment]
Ah, I see. Yes, this is not right. I changed the behaviour in the refactoring and close this here therefore.

**Comment by mustermeiszer** [comment]
I will reopen so we cose this once the main PR goes in.
