### ISSUE TITLE
Introduce decimals to TokenPrices and PoolBalances

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#754]
Currently, we have the problem that all balances in a pool are assumed to have the same decimals. 
&rarr; Conversions from orders in tranche-balance into pool-balances are done without adjusting decimals.

Furthermore, we have currently the situation that we set the token prices to `One::one()` [here](https://github.com/centrifuge/centrifuge-chain/blob/6093cca5cec4174c663e4131abb1669fcf14a050/pallets/pools/src/tranche.rs#L781).

This will set result in setting the price to `1_000_000_000_000_000_000_000_000_000,` due to the implementation of fixed point  as follows ([here](https://github.com/centrifuge/centrifuge-chain/blob/6093cca5cec4174c663e4131abb1669fcf14a050/runtime/common/src/fixed_point.rs#L1535-L1542))
```rust 
implement_fixed!(
	Rate,
	test_rate,
	u128,
	false,
	1_000_000_000_000_000_000_000_000_000,
	"_Fixed Point 128 bits unsigned with 27 precision for Rate",
);
```
As seen above the decimals are 27. But pools-balance is just a `Balance` type. 

## Proposal
* Crate a trait that allows to retrieve the decimals of a type (i.e. extend the current fixed_points impls we have)
* Provide pools with the ability to actually get decimals of the underlying `CurrencyId` (maybe extend the `CurrencyId` enum with a decimals field like acala does) and use this for conversions.

**Comment by branan** [comment]
After the refactor of the loans pallet to use `Balance`s, we now have consistent (if arbitrary) decimals across the two pallets. The number of decimal points is based on the number of decimals in the pool currency, and will be the same across both (since they are now both large integers of satoshis).

This also means that due to how `pools` tracks token pricing, the number of decimals in the tranche tokens for a given pool will automatically match the number of decimals in the pool currency.

This seems like a fine default behavior to me, but if there is a desire to have the decimals of tranche tokens be consistent across pools then we may need to refactor some things in the way we compute tranche token prices (to account for the decimals difference). This will make the code more complex for a uniformity gain that I don't think is necessarily worthwhile.

I'd propose we mark this as `resolved` due to the loans refactor to use balances, and consider the decimals of tranche tokens matching the pool currency to be "intended behavior". I'd imagine having all tokens to do with a pool use the same number of decimals will also help the frontend?

/cc @jeroen
