### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LXHLeaner** [centrifuge/centrifuge-chain#892]
I have some question,please help me solve these,I would appreciate it !
```
First Question: Can you give me a public blockchain node?

Second Question: 
      What is the thransfer crowdloanclaim-claim_reward meaning?
      What is the thransfer parachainsystem-set_validation_data meaning ?

Third Question: If we have the api or others rpc to connect with the centrifuge chain?

Fourth Question: if you can provide others document about the centrifuge chain,in addition to "https://docs.centrifuge.io/build/cent-chain/#introduction", It can make me know more about the characteristics of this chain；
```

**Comment by mustermeiszer** [comment]
> First Question: Can you give me a public blockchain node?
Not sure, I understand what you mean with that. Do you want a p2p address to a node in the centrifuge network?

>  What is the thransfer crowdloanclaim-claim_reward meaning?
This an extrinsic people can use in order to claim their rights on CFG/AIR, if they contributed in our crowdloan

>  What is the thransfer parachainsystem-set_validation_data meaning ?
Parachain internals. The relay-chain provides this data and this data is used for xcm and consensus. If you want heavy details, this will take longer.

> If we have the api or others rpc to connect with the centrifuge chain?
wss://fullnode.parachain.centrifuge.io

> if you can provide others document about the centrifuge chain,in addition to "https://docs.centrifuge.io/build/cent-chain/#introduction", It can make me know more about the characteristics of this chain；
Code is docs if the docs on the website are not sufficient for you. There are more sections than "introduction".

Small question back: What are you trying to archive?
